# https://github.com/probot/stale

daysUntilStale: 60
daysUntilClose: 7

onlyLabels: []
exemptLabels:
  - help wanted
  - good first issue

exemptProjects: false
exemptMilestones: false
exemptAssignees: false

staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

limitPerRun: 30
