language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
cache: pip
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run nosetests --nocapture tests/
